import { CitationChip } from "../ui/agent/CitationChip";
import { SourceDrawer } from "../ui/agent/SourceDrawer";
import { Badge } from "../ui/badge/Badge";
import { Button } from "../ui/button/Button";
import { DescriptionList } from "../ui/description-list/DescriptionList";
import { Panel } from "../ui/layout/Panel";

export function CitationReviewBlock() {
  return (
    <div className="grid gap-5 rounded-habibiLg bg-gray-50 p-4 xl:grid-cols-[minmax(0,1fr)_360px]">
      <Panel title="Answer review" description="Inspect the claims an agent made before publishing.">
        <div className="space-y-4 text-sm leading-7 text-gray-700">
          <p>
            The strongest lift is in North America, with response quality up 4.2% and campaign volume up 12% from the previous period.
          </p>
          <div className="flex flex-wrap gap-2">
            <CitationChip index={1} label="Regional lift summary" tone="brand" />
            <CitationChip confidence="92%" index={2} label="Attribution confidence" tone="success" />
            <CitationChip index={3} label="Budget guidance" />
          </div>
          <DescriptionList
            items={[
              { label: "Review status", value: <Badge variant="warning">Needs approval</Badge> },
              { label: "Source coverage", value: "3 cited sources" },
              { label: "Generated by", value: "Analytics Agent" },
            ]}
          />
          <div className="flex flex-wrap justify-end gap-3">
            <Button variant="secondaryGray">Request changes</Button>
            <Button>Approve answer</Button>
          </div>
        </div>
      </Panel>
      <SourceDrawer />
    </div>
  );
}
